---
# Source: netbox/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: netbox-housekeeping
  labels:
    helm.sh/chart: netbox-4.0.1
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/version: "v3.1.6-1.5.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: housekeeping
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 5
  suspend: false
  jobTemplate:
    metadata:
      labels:
        helm.sh/chart: netbox-4.0.1
        app.kubernetes.io/name: netbox
        app.kubernetes.io/instance: netbox
        app.kubernetes.io/version: "v3.1.6-1.5.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: netbox
            app.kubernetes.io/instance: netbox
            app.kubernetes.io/component: housekeeping
        spec:
          serviceAccountName: ${providers.kubernetes.outputs.app-namespace}
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
          initContainers:
            - name: kubexit
              image: karlkfi/kubexit:latest
              command: ['cp', '/bin/kubexit', '/kubexit/kubexit']
              securityContext:
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
              volumeMounts:
              - mountPath: /kubexit
                name: kubexit
          containers:
            - name: netbox-housekeeping
              securityContext:
                capabilities:
                  drop:
                  - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
              image: "netboxcommunity/netbox:v3.1.6-1.5.1"
              command:
                - /kubexit/kubexit
                - /opt/netbox/venv/bin/python
                - /opt/netbox/netbox/manage.py
                - housekeeping
              imagePullPolicy: IfNotPresent
              env:
              - name: KUBEXIT_NAME
                value: netbox-housekeeping
              - name: KUBEXIT_GRAVEYARD
                value: /graveyard
              - name: KUBEXIT_BIRTH_DEPS
                value: cloud-sql-proxy
              - name: KUBEXIT_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: KUBEXIT_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              volumeMounts:
                - name: config
                  mountPath: /etc/netbox/config/configuration.py
                  subPath: configuration.py
                  readOnly: true
                - name: config
                  mountPath: /run/config/netbox
                  readOnly: true
                - name: secrets
                  mountPath: /run/secrets/netbox
                  readOnly: true
                - name: netbox-tmp
                  mountPath: /tmp
                - name: media
                  mountPath: /opt/netbox/netbox/media
                  subPath: ""
                - mountPath: /graveyard
                  name: graveyard
                - mountPath: /kubexit
                  name: kubexit
                - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                  name: kube-api-access
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 500m
                  memory: 512Mi
            - command:
              - /kubexit/kubexit
              - /cloud_sql_proxy
              - -instances=$(CONNECTION_NAME)=tcp:5432
              env:
              - name: CONNECTION_NAME
                valueFrom:
                  secretKeyRef:
                    key: connection_name
                    name: cloudsql-instance
              - name: KUBEXIT_NAME
                value: cloud-sql-proxy
              - name: KUBEXIT_GRAVEYARD
                value: /graveyard
              - name: KUBEXIT_DEATH_DEPS
                value: netbox-housekeeping
              image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
              name: cloud-sql-proxy
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
              securityContext:
                runAsNonRoot: true
              volumeMounts:
              - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                name: kube-api-access
              - mountPath: /graveyard
                name: graveyard
              - mountPath: /kubexit
                name: kubexit
              lifecycle:
                preStop:
                  exec:
                    command: ['sleep', '10']
          volumes:
            - name: graveyard
              emptyDir:
                medium: Memory
            - name: kubexit
              emptyDir: {}
            - name: config
              configMap:
                name: netbox
            - name: secrets
              projected:
                sources:
                  - secret:
                      name: "netbox"
                      items:
                        # Used by our configuration
                        - key: email_password
                          path: email_password
                        - key: napalm_password
                          path: napalm_password
                        - key: secret_key
                          path: secret_key
                  - secret:
                      name: "psql-netbox-user"
                      items:
                        - key: "postgresql-password"
                          path: db_password
                  - secret:
                      name: "netbox"
                      items:
                        - key: "redis_tasks_password"
                          path: redis_tasks_password
                  - secret:
                      name: "netbox"
                      items:
                        - key: "redis_cache_password"
                          path: redis_cache_password
            - name: netbox-tmp
              emptyDir:
                medium: Memory
            - name: media
              emptyDir: {}
            - name: kube-api-access
              projected:
                defaultMode: 420 # 0644
                sources:
                  - serviceAccountToken:
                      expirationSeconds: 3607
                      path: token
                  - configMap:
                      items:
                        - key: ca.crt
                          path: ca.crt
                      name: kube-root-ca.crt
                  - downwardAPI:
                      items:
                        - fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.namespace
                          path: namespace
          restartPolicy: OnFailure
