kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-viewer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-viewer
subjects:
- kind: ServiceAccount
  name: ${providers.kubernetes.outputs.app-namespace}
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-viewer
  apiGroup: rbac.authorization.k8s.io  