{{- $fullName := include "netbox-ingress.fullname" . -}}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ $fullName }}
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    port: 8000
    type: HTTP
    requestPath: /healthcheck