{{- if and .Values.ingress.tls.enabled .Values.ingress.tls.httpRedirect -}}
{{- $fullName := include "netbox-ingress.fullname" . -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ $fullName }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "301"
{{- end }}
