apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbox-ingress.fullname" . }}
  labels:
    {{- include "netbox-ingress.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default": "netbox-ingress"}'
    cloud.google.com/neg: '{"ingress": true}'
  {{- if or .Values.commonAnnotations .Values.service.annotations }}
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nginx-http
      protocol: TCP
      name: nginx-http
  selector:
    app.kubernetes.io/component: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/name: netbox
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}